name: "pull request"
on: 
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  tests:
    name: "run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: "actually run the tests"
        run: |
          go test -v -race ./...